### ISSUE TITLE
snr calculation 

### ISSUE THREAD

**Issue by rosella1234** [samuelstjean/autodmri#8]
I used your autodmri code to compute noise parameters of a phantom with different configuration of parallel imaging and multiband in the acquisition sequence. I thus obtained N sigma and the relative mask for each kind of acquisition. I would like to compare the SNR among the 5 cases. What is the best way to do so? I mean for practically calculate SNR. I thought of using as SIGNAL the image itself denoised using NLSAM algorithm but, as regards NOISE, which measure I previously obtained should I use? since SNR is defined as SIGNAL/std(NOISE) I thought of using sigma.nii.gz. Is that correct?
thank you in advance,
Rosella

**Comment by samuelstjean** [comment]
Yes, that should be it. SNR calculation though are probably only meaningful in that context for different sequences / scanners and on a global level though, since it would be easy to inflate it artificially with higher signal values. Kind of like what the scanner gives you in terms of relative SNR when changing parameters.
